$schema: https://cdn.jsdelivr.net/npm/@micro-lc/interfaces@latest/schemas/v2/config.schema.json
version: 2

layout:
  sources: https://cdn.jsdelivr.net/npm/@micro-lc/layout@latest/dist/mlc-layout.js
  content:
    - tag: mlc-layout
      properties:
        mode: topBar
        logo:
          url: ../../../../img/favicon.png
        menuItems:
          - icon:
              library: '@ant-design/icons-svg'
              selector: GlobalOutlined
            id: react
            label: React parcel
            type: application

applications:
  react:
    integrationMode: parcel
    route: ./
    entry: ../../../../applications/react-hash-router/
